services:
  - type: web
    name: pdf-apis
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y --no-install-recommends ghostscript poppler-utils libreoffice-writer libreoffice-calc fonts-liberation ttf-dejavu
      npm install
    startCommand: node server.js
